catalog:
  globals: ^17.4.0
  '@eslint/js': ^10.0.1
  '@eslint/eslintrc': ^3.3.4
  '@typescript-eslint/eslint-plugin': ^8.56.1
  '@typescript-eslint/parser': ^8.56.1
  eslint: ^9.39.3
  eslint-config-prettier: ^10.1.8
  eslint-plugin-ember: ^12.7.5
  eslint-plugin-n: ^17.24.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-qunit: ^8.2.6
  prettier: ^3.8.1
  stylelint: ^17.4.0
  jiti: ^2.6.1
  typescript-eslint: ^8.56.1
  ember-template-lint: ^7.9.3
  prettier-plugin-ember-template-tag: ^2.1.3
  stylelint-config-standard: ^40.0.0
  '@babel/eslint-parser': ^7.28.6
  decorator-transforms: ^2.3.1
  '@babel/preset-env': ^7.29.0
  '@glint/tsserver-plugin': ^2.1.0

overrides:
  ember-metis>ember-fetch: '-'

packageExtensions:
  ember-metis:
    peerDependenciesMeta:
      ember-cli-fastboot:
        optional: true
