catalog:
  '@ember-data/debug': 5.8.1
  '@warp-drive/build-config': 5.8.1
  '@warp-drive/core': 5.8.1
  '@warp-drive/core-types': 5.8.1
  '@warp-drive/ember': 5.8.1
  '@warp-drive/json-api': 5.8.1
  '@warp-drive/legacy': 5.8.1
  '@warp-drive/schema-record': 5.8.1
  '@warp-drive/utilities': 5.8.1

overrides:
  ember-metis>ember-fetch: '-'

packageExtensions:
  ember-metis:
    peerDependenciesMeta:
      ember-cli-fastboot:
        optional: true
