steps:
  changeset:
    image: alpine/git:2.49.0
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep "\.changeset/.*\.md"
when:
  - evaluate: 'CI_PIPELINE_EVENT == "pull_request" && CI_COMMIT_TARGET_BRANCH == "master" && not (CI_COMMIT_PULL_REQUEST_LABELS contains "dependabot")'
