steps:
  install:
    image: node:22-slim
    commands:
      - npm i -g corepack@0.33
      - corepack enable
      - pnpm i --frozen-lockfile
  lint:
    image: node:22-slim
    commands:
      - npm i -g corepack@0.33
      - corepack enable
      - pnpm lint
  test:
    image: node:22-slim
    commands:
      - npm i -g corepack@0.33
      - corepack enable
      - pnpm test:ember
when:
  event: pull_request
