steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci
  lint:
    image: danlynn/ember-cli:4.12.1
    group: lint
    commands:
      - npm run lint
  test:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm run test:ember
when:
  event: pull_request
