steps:
  install:
    image: node:20-slim
    commands:
      - npm ci
  lint:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint
  test:
    image: node:20-slim
    commands:
      - npm run test:ember
when:
  event: pull_request
